# Generated by Django 4.1.7 on 2023-03-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
