# Generated by Django 4.1.7 on 2023-03-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_author_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='gender',
        ),
    ]
