# Generated by Django 4.1.7 on 2023-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_author_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='login_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='login_token_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
