# Generated by Django 4.2.6 on 2023-10-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(default='12345678', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/maineditor/images')),
                ('designation', models.CharField(max_length=100)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('login_token', models.CharField(blank=True, max_length=255, null=True)),
                ('login_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Main Editor',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/conference/images')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('paper_submission_deadline', models.DateField()),
                ('paper_review_deadline', models.DateField()),
                ('paper_acceptance_deadline', models.DateField()),
                ('paper_publish_deadline', models.DateField()),
                ('no_of_papers', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_editor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maineditor.maineditor')),
            ],
            options={
                'verbose_name_plural': 'Conferences',
            },
        ),
    ]
